### ISSUE TITLE
Rad Racer 2 bug

### ISSUE THREAD

**Issue by Tatsuya79** [negativeExponent/libretro-fceumm#36]
Rad Racer II (USA).nes CRC 39D371EC has issues on your branch.
It's fine on the libretro repo and in Nestopia.

![Rad Racer II (USA)-241001-114151](https://github.com/user-attachments/assets/fa17e766-daaa-45e4-bddd-7429946a5ec0)

**Comment by negativeExponent** [comment]
thanks. typo in handling 4-screen mirroring for mmc3.

fixed in latest commit.
